### PR TITLE
Added Sponsors page

### PR DESCRIPTION
**Pull request by icepeda**
## What's new? ##

- Added Sponsors Page

### CODE REVIEW

**Comment by eatskolnikov** [comment]
Hey @icepeda I'm getting a cors error when trying to test, how did you get over that? 

Screen Shot 2019-09-16 at 9 41 48 PM

**Comment by Cesarlachapelle** [comment]
@eatskolnikov to test it you have to use a extension for the cors, maybe can work with this extension : https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=es

**Comment by icepeda** [comment]
No sabia que tenia un extension activado. Este he estado usando: https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en

**Comment by eatskolnikov** [comment]
Make sure framed sections are aligned and have the same size

Screen Shot 2019-09-16 at 9 48 49 PM

**Comment by Cesarlachapelle** [comment]
I think that it is better to move the requests to an endpoint in the backend, so that everyone who tests that section does not have to install the extension to test

**Comment by eatskolnikov** [comment]
Check the documentation for the opencollective graphql
https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff

**Comment by icepeda** [comment]
Fixes has been made. Thanks for the feedback guys, hope they keep on coming.

The primary change was made in the controller. Now instead of calling opencollective from AJAX, i make the call from the controller, this way we can avoid CORS issues for this specific case.

**UI Changes**
usersteam

(pinedax chin is a bit to large 😅 ):
Users-After

**Pull request merged**
